[core.option]
# The protocol type for rendering images of commit graphs.
# The value specified in the command line argument takes precedence.
# type: enum (possible values: "auto", "iterm", "kitty")
protocol = "kitty"
# The commit ordering algorithm.
# The value specified in the command line argument takes precedence.
# type: enum (possible values: "chrono", "topo")
order = "chrono"
# The character width that a graph image unit cell occupies.
# The value specified in the command line argument takes precedence.
# type: enum (possible values: "auto", "double", "single")
graph_width = "auto"
# The initial selection of commit when starting the application.
# The value specified in the command line argument takes precedence.
# type: enum (possible values: "latest", "head")
initial_selection = "latest"

[core.search]
# Whether to enable ignore case by default.
# type: boolean
ignore_case = true
# Whether to enable fuzzy matching by default.
# type: boolean
fuzzy = true

[core.user_command]
# The command definition for generating the content displayed in the user command view.
# Multiple commands can be specified in the format commands_{n}.
# For details about user command, see the separate User command section.
# type: object
commands_1 = { name = "git diff", commands = ["git", "--no-pager", "diff", "--color=always", "{{first_parent_hash}}", "{{target_hash}}"]}
# The number of spaces to replace tabs in the user command output.
# type: u16
tab_width = 2

[ui.common]
# The type of a cursor to display in the input.
# If `cursor_type = "Native"` is set, the terminal native cursor is used.
# If `cursor_type = { "Virtual" = "|" }` is set, a virtual cursor with the specified string will be used.
# type: enum
cursor_type = "Native"

[ui.list]
# The minimum width of a subject in the commit list.
# type: u16
subject_min_width = 20
# The date format of a author date in the commit list.
# The format must be specified in strftime format.
# https://docs.rs/chrono/latest/chrono/format/strftime/index.html
# type: string
date_format = "%m/%d/%Y"
# The width of a author date in the commit list.
# type: u16
date_width = 10
# Whether to show a author date in the commit list in local timezone.
# type: boolean
date_local = true
# The width of a author name in the commit list.
# type: u16
name_width = 10

[ui.detail]
# The height of a commit detail area.
# type: u16
height = 20
# The date format of a author/committer date in the commit detail.
# The format must be specified in strftime format.
# https://docs.rs/chrono/latest/chrono/format/strftime/index.html
# type: string
date_format = "%m/%d/%Y %H:%M %z"
# Whether to show a author/committer date in the commit list in local timezone.
# type: boolean
date_local = true

[ui.user_command]
# The height of a user command area.
# type: u16
height = 20

[ui.refs]
# The width of a refs list area.
# type: u16
width = 26

[graph.color]
# Colors should be specified in the format #RRGGBB or #RRGGBBAA.

# Based on
# https://stephango.com/flexoki

# Array of colors used for the commit graph.
# type: array of strings
branches = [
  "#CE5D97", # magenta-400
  "#8B7EC8", # purple-400
  "#4385BE", # blue-400
  "#3AA99F", # cyan-400
  "#879A39", # green-400
  "#D0A215", # yellow-400
  "#DA702C", # orange-400
  "#D14D41", # red-400 
]
# Color of the edge surrounding the commit circles in the graph.
# type: string
edge = "#282726" # ui
# Background color of the commit graph.
# type: string
background = "#100F0F" # bg

[color]
# The colors of each element of the application.
# Note: Graph colors are specified with [graph.color].
#
# Colors should be specified in one of the following formats:
# - ANSI color name
#   - "red", "bright-blue", "light-red", "reset", ...
# - 8-bit color (256-color) index values
#   - "34", "128", "255", ...
# - 24-bit true color hex codes
#   - "#abcdef", ...
# type: string
fg = "reset"
bg = "reset"
list_selected_fg = "#CECDC3" # tx
list_selected_bg = "#1C1B1A" # bg-2
list_ref_paren_fg = "#D0A215" # yellow-400
list_ref_branch_fg = "#879A39" # green-400
list_ref_remote_branch_fg = "#D14D41" # red-400
list_ref_tag_fg = "#D0A215" # yellow-400
list_ref_stash_fg = "#CE5D97" # magenta-400
list_head_fg = "#D0A215" # yellow-400
list_subject_fg = "reset"
list_name_fg = "#8B7EC8" # purple-400
list_hash_fg = "#D0A215" # yellow-400
list_date_fg = "#575653" # tx-3
list_match_fg = "#100F0F" # black
list_match_bg = "#D0A215" # yellow-400
detail_email_fg = "#4385BE" # blue-400
detail_ref_branch_fg = "#879A39" # green-400
detail_ref_remote_branch_fg = "#D14D41" # red-400
detail_ref_tag_fg = "#D0A215" # yellow-400
detail_file_change_add_fg = "#879A39" # green-400
detail_file_change_modify_fg = "#D0A215" # yellow-400
detail_file_change_delete_fg = "#D14D41" # red-400
detail_file_change_move_fg = "#CE5D97" # magenta-400
ref_selected_fg = "#CECDC3" # tx
ref_selected_bg = "#1C1B1A" # bg-2
help_block_title_fg = "#879A39" # green-400
help_key_fg = "#D0A215" # yellow-400
virtual_cursor_fg = "reset"
status_input_fg = "reset"
status_input_transient_fg = "#1C1B1A" # bg-2
status_info_fg = "#3AA99F" # cyan-400
status_success_fg = "#879A39" # green-400
status_warn_fg = "#D0A215" # yellow-400
status_error_fg = "#D14D41" # red-400
divider_fg = "#1C1B1A" # bg-2

[keybind]
# See ./assets/default-keybind.toml for a specific example configuration.
# ...
