prSections:
- title: My Pull Requests
  filters: is:open author:@me updated:>={{ nowModify "-3w" }}
- title: Needs Review
  filters: is:open review-requested:@me
issuesSections:
- title: My Issues
  filters: is:open author:@me
- title: Assigned
  filters: is:open assignee:@me
repo:
  branchesRefetchIntervalSeconds: 30
  prsRefetchIntervalSeconds: 60
defaults:
  preview:
    open: true
    width: 80
  prsLimit: 20
  issuesLimit: 20
  prApproveComment: LGTM
  view: repo
  layout:
    prs:
      updatedAt:
        width: 5
      createdAt:
        width: 5
      repo:
        width: 20
      author:
        width: 15
      authorIcon:
        hidden: false
      assignees:
        width: 20
        hidden: true
      base:
        width: 15
        hidden: true
      lines:
        width: 15
    issues:
      updatedAt:
        width: 5
      createdAt:
        width: 5
      repo:
        width: 15
      creator:
        width: 10
      creatorIcon:
        hidden: false
      assignees:
        width: 20
        hidden: true
  refetchIntervalMinutes: 30
keybindings:
  universal: []
  issues: []
  prs: []
  branches: []
repoPaths: {}
pager:
  diff: "delta"
confirmQuit: false
showAuthorIcons: true
smartFilteringAtLaunch: true
theme:
  ui:
    sectionsShowCount: true
    table:
      showSeparator: true
      compact: false
  colors:
    text:
      primary: "#CECDC3"
      secondary: "#878580"
      inverted: "#100F0F"
      faint: "#575653"
      warning: "#DA702C"
      success: "#879A39"
      error: "#D14D41"
    background:
      selected: "#1C1B1A"
    border:
      primary: "#282726"
      secondary: "#343331"
      faint: "#403E3C"
